POST http://localhost:3000/login/
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk0MjU4MzU4fQ.oi7hQHiS1M4FZTJ39eJPTkI-GI1ItAjzEqF65OU5H10

{
  "username": "christopher_phillips",
  "password": "christy@123"
} 
### 
GET http://localhost:3000/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk0MjU4MzU4fQ.oi7hQHiS1M4FZTJ39eJPTkI-GI1ItAjzEqF65OU5H10 

### 
GET http://localhost:3000/states/8/ 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk0MjU4MzU4fQ.oi7hQHiS1M4FZTJ39eJPTkI-GI1ItAjzEqF65OU5H10 

###
POST http://localhost:3000/districts/
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk0MjU4MzU4fQ.oi7hQHiS1M4FZTJ39eJPTkI-GI1ItAjzEqF65OU5H10 

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
} 
### 
GET http://localhost:3000/districts/322/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk0MjU4MzU4fQ.oi7hQHiS1M4FZTJ39eJPTkI-GI1ItAjzEqF65OU5H10 
### 
DELETE http://localhost:3000/districts/321/ 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk0MjU4MzU4fQ.oi7hQHiS1M4FZTJ39eJPTkI-GI1ItAjzEqF65OU5H10 

### 
PUT http://localhost:3000/districts/322 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk0MjU4MzU4fQ.oi7hQHiS1M4FZTJ39eJPTkI-GI1ItAjzEqF65OU5H10 


{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}






